# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@holesail/hyper-cmd-lib-net-0.1.0" = {
      name = "_at_holesail_slash_hyper-cmd-lib-net";
      packageName = "@holesail/hyper-cmd-lib-net";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@holesail/hyper-cmd-lib-net/-/hyper-cmd-lib-net-0.1.0.tgz";
        sha512 = "Ru3aOXVXhIzv3gHQm9eLAEQhUbJuN9jGYywvH6ausHziORuIQxltdNFTA638RpvzQlIQB5r2E+AK/9hhie8i5g==";
      };
    };
    "@hyperswarm/secret-stream-6.6.3" = {
      name = "_at_hyperswarm_slash_secret-stream";
      packageName = "@hyperswarm/secret-stream";
      version = "6.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hyperswarm/secret-stream/-/secret-stream-6.6.3.tgz";
        sha512 = "F/EF5KLUqjkTNFof1K5dz57CwrwjSzG0XxZe2X9t/2/mG5iQ28yJIwNcVabkWS1Wk2ZB719piVGKk6YbwkJ0aQ==";
      };
    };
    "@pm2/agent-2.0.4" = {
      name = "_at_pm2_slash_agent";
      packageName = "@pm2/agent";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@pm2/agent/-/agent-2.0.4.tgz";
        sha512 = "n7WYvvTJhHLS2oBb1PjOtgLpMhgImOq8sXkPBw6smeg9LJBWZjiEgPKOpR8mn9UJZsB5P3W4V/MyvNnp31LKeA==";
      };
    };
    "@pm2/io-6.0.1" = {
      name = "_at_pm2_slash_io";
      packageName = "@pm2/io";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@pm2/io/-/io-6.0.1.tgz";
        sha512 = "KiA+shC6sULQAr9mGZ1pg+6KVW9MF8NpG99x26Lf/082/Qy8qsTCtnJy+HQReW1A9Rdf0C/404cz0RZGZro+IA==";
      };
    };
    "@pm2/js-api-0.8.0" = {
      name = "_at_pm2_slash_js-api";
      packageName = "@pm2/js-api";
      version = "0.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@pm2/js-api/-/js-api-0.8.0.tgz";
        sha512 = "nmWzrA/BQZik3VBz+npRcNIu01kdBhWL0mxKmP1ciF/gTcujPTQqt027N9fc1pK9ERM8RipFhymw7RcmCyOEYA==";
      };
    };
    "@pm2/pm2-version-check-1.0.4" = {
      name = "_at_pm2_slash_pm2-version-check";
      packageName = "@pm2/pm2-version-check";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@pm2/pm2-version-check/-/pm2-version-check-1.0.4.tgz";
        sha512 = "SXsM27SGH3yTWKc2fKR4SYNxsmnvuBQ9dd6QHtEWmiZ/VqaOYPAIlS8+vMcn27YLtAEBGvNRSh3TPNvtjZgfqA==";
      };
    };
    "@tootallnate/quickjs-emscripten-0.23.0" = {
      name = "_at_tootallnate_slash_quickjs-emscripten";
      packageName = "@tootallnate/quickjs-emscripten";
      version = "0.23.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tootallnate/quickjs-emscripten/-/quickjs-emscripten-0.23.0.tgz";
        sha512 = "C5Mc6rdnsaJDjO3UpGW/CQTHtCKaYlScZTly4JIu97Jxo/odCiH0ITnDXSJPTOrEKk/ycSZ0AOgTmkDtkOsvIA==";
      };
    };
    "agent-base-7.1.1" = {
      name = "agent-base";
      packageName = "agent-base";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/agent-base/-/agent-base-7.1.1.tgz";
        sha512 = "H0TSyFNDMomMNJQBn8wFV5YC/2eJ+VXECwOadZJT554xP6cODZHPX3H9QMQECxvrgiSOP1pHjy1sMWQVYJOUOA==";
      };
    };
    "amp-0.3.1" = {
      name = "amp";
      packageName = "amp";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/amp/-/amp-0.3.1.tgz";
        sha512 = "OwIuC4yZaRogHKiuU5WlMR5Xk/jAcpPtawWL05Gj8Lvm2F6mwoJt4O/bHI+DHwG79vWd+8OFYM4/BzYqyRd3qw==";
      };
    };
    "amp-message-0.1.2" = {
      name = "amp-message";
      packageName = "amp-message";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/amp-message/-/amp-message-0.1.2.tgz";
        sha512 = "JqutcFwoU1+jhv7ArgW38bqrE+LQdcRv4NxNw0mp0JHQyB6tXesWRjtYKlDgHRY2o3JE5UTaBGUK8kSWUdxWUg==";
      };
    };
    "ansi-colors-4.1.3" = {
      name = "ansi-colors";
      packageName = "ansi-colors";
      version = "4.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-colors/-/ansi-colors-4.1.3.tgz";
        sha512 = "/6w/C21Pm1A7aZitlI5Ni/2J6FFQN8i1Cvz3kHABAAbw93v/NlvKdVOqz7CCWz/3iv/JplRSEEZ83XION15ovw==";
      };
    };
    "ansi-parser-3.2.10" = {
      name = "ansi-parser";
      packageName = "ansi-parser";
      version = "3.2.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-parser/-/ansi-parser-3.2.10.tgz";
        sha512 = "CGKGIbd678lm15IXJXI1cTyOVAnMQw0jES+klW/yIc+GzYccsYanLMhczPIIj2hE64B79g75QfiuWrEWd6nJdg==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "anymatch-3.1.3" = {
      name = "anymatch";
      packageName = "anymatch";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/anymatch/-/anymatch-3.1.3.tgz";
        sha512 = "KMReFUr0B4t+D+OBkjR3KYqvocp2XaSzO55UcB6mgQMd3KbcE+mWTyvVV7D/zsdEbNnV6acZUutkiHQXvTr1Rw==";
      };
    };
    "argparse-2.0.1" = {
      name = "argparse";
      packageName = "argparse";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-2.0.1.tgz";
        sha512 = "8+9WqebbFzpX9OR+Wa6O29asIogeRMzcGtAINdpMHHyAg10f05aSFVBbcEqGf/PXw1EjAZ+q2/bEBg3DvurK3Q==";
      };
    };
    "ast-types-0.13.4" = {
      name = "ast-types";
      packageName = "ast-types";
      version = "0.13.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/ast-types/-/ast-types-0.13.4.tgz";
        sha512 = "x1FCFnFifvYDDzTaLII71vG5uvDwgtmDTEVWAxrgeiR8VjMONcCXJx7E+USjDtHlwFmt9MysbqgF9b9Vjr6w+w==";
      };
    };
    "async-2.6.4" = {
      name = "async";
      packageName = "async";
      version = "2.6.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-2.6.4.tgz";
        sha512 = "mzo5dfJYwAn29PeiJ0zvwTo04zj8HDJj0Mn8TD7sno7q12prdbnasKJHhkm2c1LgrhlJ0teaea8860oxi51mGA==";
      };
    };
    "async-3.2.6" = {
      name = "async";
      packageName = "async";
      version = "3.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-3.2.6.tgz";
        sha512 = "htCUDlxyyCLMgaM3xXg0C0LW2xqfuQ6p05pCEIsXuyQ+a1koYKTuBMzRNwmybfLgvJDMd0r1LTn4+E0Ti6C2AA==";
      };
    };
    "b4a-1.6.6" = {
      name = "b4a";
      packageName = "b4a";
      version = "1.6.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/b4a/-/b4a-1.6.6.tgz";
        sha512 = "5Tk1HLk6b6ctmjIkAcU/Ujv/1WqiDl0F0JdRCR80VsOcUlHcu7pWeWRlOqQLHfDEsVx9YH/aif5AG4ehoCtTmg==";
      };
    };
    "bare-dns-1.0.4" = {
      name = "bare-dns";
      packageName = "bare-dns";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/bare-dns/-/bare-dns-1.0.4.tgz";
        sha512 = "O+IpPJLJb+fEY78Uh/z84kbEfDg60lhYS9XajSVVLjlLOMxtWborAPcw7rVXzymHZrdcymaUa7jX9XI5QJ+p0A==";
      };
    };
    "bare-events-2.4.2" = {
      name = "bare-events";
      packageName = "bare-events";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bare-events/-/bare-events-2.4.2.tgz";
        sha512 = "qMKFd2qG/36aA4GwvKq8MxnPgCQAmBWmSyLWsJcbn8v03wvIPQ/hG1Ms8bPzndZxMDoHpxez5VOS+gC9Yi24/Q==";
      };
    };
    "bare-net-1.0.1" = {
      name = "bare-net";
      packageName = "bare-net";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bare-net/-/bare-net-1.0.1.tgz";
        sha512 = "eTMpS2fxXiuz5eMvMGEkJBsgIfanPFoniiepCmgbCRQVdAIjg1wutaRzHTqRJpuG4yCzrcar581AIPf1XzyH8g==";
      };
    };
    "bare-pipe-3.3.6" = {
      name = "bare-pipe";
      packageName = "bare-pipe";
      version = "3.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/bare-pipe/-/bare-pipe-3.3.6.tgz";
        sha512 = "ULbZEhRiovQntgy3pcltH/IvyO3rsPjuqVLMAIshE2J+VRK/cc0x5ACg4Nq7KwkgG9zK4vBhvc7PP1p1AcdJ5Q==";
      };
    };
    "bare-stream-2.3.0" = {
      name = "bare-stream";
      packageName = "bare-stream";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bare-stream/-/bare-stream-2.3.0.tgz";
        sha512 = "pVRWciewGUeCyKEuRxwv06M079r+fRjAQjBEK2P6OYGrO43O+Z0LrPZZEjlc4mB6C2RpZ9AxJ1s7NLEtOHO6eA==";
      };
    };
    "bare-tcp-1.9.0" = {
      name = "bare-tcp";
      packageName = "bare-tcp";
      version = "1.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bare-tcp/-/bare-tcp-1.9.0.tgz";
        sha512 = "SXM7A39qT3xwjxPr9jhUfgJuTP5M0miInmMSv9LlzKs/WRSTf9Ee7WS8jCtA8vrvHLfIiDvMRJhi4UR7nMaC5A==";
      };
    };
    "basic-ftp-5.0.5" = {
      name = "basic-ftp";
      packageName = "basic-ftp";
      version = "5.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/basic-ftp/-/basic-ftp-5.0.5.tgz";
        sha512 = "4Bcg1P8xhUuqcii/S0Z9wiHIrQVPMermM1any+MX5GeGD7faD3/msQUDGLol9wOcz4/jbg/WJnGqoJF6LiBdtg==";
      };
    };
    "binary-extensions-2.3.0" = {
      name = "binary-extensions";
      packageName = "binary-extensions";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/binary-extensions/-/binary-extensions-2.3.0.tgz";
        sha512 = "Ceh+7ox5qe7LJuLHoY0feh3pHuUDHAcRUeyL2VYghZwfpkNIy/+8Ocg0a3UuSoYzavmylwuLWQOf3hl0jjMMIw==";
      };
    };
    "bits-to-bytes-1.3.0" = {
      name = "bits-to-bytes";
      packageName = "bits-to-bytes";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bits-to-bytes/-/bits-to-bytes-1.3.0.tgz";
        sha512 = "OJoHTpFXS9bXHBCekGTByf3MqM8CGblBDIduKQeeVVeiU9dDWywSSirXIBYGgg3d1zbVuvnMa1vD4r6PA0kOKg==";
      };
    };
    "blake2b-2.1.4" = {
      name = "blake2b";
      packageName = "blake2b";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/blake2b/-/blake2b-2.1.4.tgz";
        sha512 = "AyBuuJNI64gIvwx13qiICz6H6hpmjvYS5DGkG6jbXMOT8Z3WUJ3V1X0FlhIoT1b/5JtHE3ki+xjtMvu1nn+t9A==";
      };
    };
    "blake2b-wasm-2.4.0" = {
      name = "blake2b-wasm";
      packageName = "blake2b-wasm";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/blake2b-wasm/-/blake2b-wasm-2.4.0.tgz";
        sha512 = "S1kwmW2ZhZFFFOghcx73+ZajEfKBqhP82JMssxtLVMxlaPea1p9uoLiUZ5WYyHn0KddwbLc+0vh4wR0KBNoT5w==";
      };
    };
    "blessed-0.1.81" = {
      name = "blessed";
      packageName = "blessed";
      version = "0.1.81";
      src = fetchurl {
        url = "https://registry.npmjs.org/blessed/-/blessed-0.1.81.tgz";
        sha512 = "LoF5gae+hlmfORcG1M5+5XZi4LBmvlXTzwJWzUlPryN/SJdSflZvROM2TwkT0GMpq7oqT48NRd4GS7BiVBc5OQ==";
      };
    };
    "blind-relay-1.3.3" = {
      name = "blind-relay";
      packageName = "blind-relay";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/blind-relay/-/blind-relay-1.3.3.tgz";
        sha512 = "J49HZaRLA+jgmIA+J01x0NzDtNMQVzuFfz7CnLLijIUMJkxTbaexIGI/tfk6LONcr/+INmgbS8gMLeuaRvfreA==";
      };
    };
    "bodec-0.1.0" = {
      name = "bodec";
      packageName = "bodec";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bodec/-/bodec-0.1.0.tgz";
        sha512 = "Ylo+MAo5BDUq1KA3f3R/MFhh+g8cnHmo8bz3YPGhI1znrMaf77ol1sfvYJzsw3nTE+Y2GryfDxBaR+AqpAkEHQ==";
      };
    };
    "bogon-1.1.0" = {
      name = "bogon";
      packageName = "bogon";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bogon/-/bogon-1.1.0.tgz";
        sha512 = "a6SnToksXHuUlgeMvI/txWmTcKz7c7iBa8f0HbXL4toN1Uza/CTQ4F7n9jSDX49TCpxv3KUP100q4sZfwLyLiw==";
      };
    };
    "braces-3.0.3" = {
      name = "braces";
      packageName = "braces";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-3.0.3.tgz";
        sha512 = "yQbXgO/OSZVD2IsiLlro+7Hf6Q18EJrKSEsdoMzKePKXct3gvD8oLcOQdIzGupr5Fj+EDe8gO/lxc1BzfMpxvA==";
      };
    };
    "buffer-from-1.1.2" = {
      name = "buffer-from";
      packageName = "buffer-from";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-from/-/buffer-from-1.1.2.tgz";
        sha512 = "E+XQCRwSbaaiChtv6k6Dwgc+bx+Bs6vuKJHHl5kox/BaKbhiXzqQOwK4cO22yElGp2OCmjwVhT3HmxgyPGnJfQ==";
      };
    };
    "bufferutil-4.0.8" = {
      name = "bufferutil";
      packageName = "bufferutil";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/bufferutil/-/bufferutil-4.0.8.tgz";
        sha512 = "4T53u4PdgsXqKaIctwF8ifXlRTTmEPJ8iEPWFdGZvcf7sbwYo6FKFEX9eNNAnzFZ7EzJAQ3CJeOtCRA4rDp7Pw==";
      };
    };
    "chacha20-universal-1.0.4" = {
      name = "chacha20-universal";
      packageName = "chacha20-universal";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/chacha20-universal/-/chacha20-universal-1.0.4.tgz";
        sha512 = "/IOxdWWNa7nRabfe7+oF+jVkGjlr2xUL4J8l/OvzZhj+c9RpMqoo3Dq+5nU1j/BflRV4BKnaQ4+4oH1yBpQG1Q==";
      };
    };
    "chalk-3.0.0" = {
      name = "chalk";
      packageName = "chalk";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-3.0.0.tgz";
        sha512 = "4D3B6Wf41KOYRFdszmDqMCGq5VV/uMAB273JILmO+3jAlh8X4qDtdtgCR3fxtbLEMzSx22QdhnDcJvu2u1fVwg==";
      };
    };
    "charm-0.1.2" = {
      name = "charm";
      packageName = "charm";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/charm/-/charm-0.1.2.tgz";
        sha512 = "syedaZ9cPe7r3hoQA9twWYKu5AIyCswN5+szkmPBe9ccdLrj4bYaCnLVPTLd2kgVRc7+zoX4tyPgRnFKCj5YjQ==";
      };
    };
    "chokidar-3.6.0" = {
      name = "chokidar";
      packageName = "chokidar";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chokidar/-/chokidar-3.6.0.tgz";
        sha512 = "7VT13fmjotKpGipCW9JEQAusEPE+Ei8nl6/g4FBAmIm0GOOLMua9NDDo/DWp0ZAxCr3cPq5ZpBqmPAQgDda2Pw==";
      };
    };
    "cli-box-6.0.10" = {
      name = "cli-box";
      packageName = "cli-box";
      version = "6.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-box/-/cli-box-6.0.10.tgz";
        sha512 = "6jjSF6G1gOXaCyBQJKo3L3lZKxP8jzdECG7FBiA4m2w7K8jBxXXwsMb75fBLwoVwOtKwvgKjLJurw8HU5XNciw==";
      };
    };
    "cli-tableau-2.0.1" = {
      name = "cli-tableau";
      packageName = "cli-tableau";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-tableau/-/cli-tableau-2.0.1.tgz";
        sha512 = "he+WTicka9cl0Fg/y+YyxcN6/bfQ/1O3QmgxRXDhABKqLzvoOSM4fMzp39uMyLBulAFuywD2N7UaoQE7WaADxQ==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "colors-1.4.0" = {
      name = "colors";
      packageName = "colors";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.4.0.tgz";
        sha512 = "a+UqTh4kgZg/SlGvfbzDHpgRu7AAQOmmqRHJnxhRZICKFUT91brVhNNt58CMWU9PsBbv3PDCZUHbVxuDiH2mtA==";
      };
    };
    "commander-2.15.1" = {
      name = "commander";
      packageName = "commander";
      version = "2.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.15.1.tgz";
        sha512 = "VlfT9F3V0v+jr4yxPc5gg9s62/fIVWsd2Bk2iD435um1NlGMYdVCq+MjcXnhYq2icNOizHr1kK+5TI6H0Hy0ag==";
      };
    };
    "compact-encoding-2.15.0" = {
      name = "compact-encoding";
      packageName = "compact-encoding";
      version = "2.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/compact-encoding/-/compact-encoding-2.15.0.tgz";
        sha512 = "af/NomxL9Mo0lqCk++rxLLDZI+lJqeBrPt4dK6FbjxTCEhfC9yQAIoO6yq9ixyCirce0luQwErkwJrhem6clxA==";
      };
    };
    "compact-encoding-bitfield-1.0.0" = {
      name = "compact-encoding-bitfield";
      packageName = "compact-encoding-bitfield";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/compact-encoding-bitfield/-/compact-encoding-bitfield-1.0.0.tgz";
        sha512 = "3nMVKUg+PF72UHfainmCL8uKvyWfxsjqOtUY+HiMPGLPCTjnwzoKfFAMo1Ad7nwTPdjBqtGK5b3BOFTFW4EBTg==";
      };
    };
    "compact-encoding-net-1.2.0" = {
      name = "compact-encoding-net";
      packageName = "compact-encoding-net";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/compact-encoding-net/-/compact-encoding-net-1.2.0.tgz";
        sha512 = "LVXpNpF7PGQeHRVVLGgYWzuVoYAaDZvKUsUxRioGfkotzvOh4AzoQF1HBH3zMNaSnx7gJXuUr3hkjnijaH/Eng==";
      };
    };
    "croner-4.1.97" = {
      name = "croner";
      packageName = "croner";
      version = "4.1.97";
      src = fetchurl {
        url = "https://registry.npmjs.org/croner/-/croner-4.1.97.tgz";
        sha512 = "/f6gpQuxDaqXu+1kwQYSckUglPaOrHdbIlBAu0YuW8/Cdb45XwXYNUBXg3r/9Mo6n540Kn/smKcZWko5x99KrQ==";
      };
    };
    "culvert-0.1.2" = {
      name = "culvert";
      packageName = "culvert";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/culvert/-/culvert-0.1.2.tgz";
        sha512 = "yi1x3EAWKjQTreYWeSd98431AV+IEE0qoDyOoaHJ7KJ21gv6HtBXHVLX74opVSGqcR8/AbjJBHAHpcOy2bj5Gg==";
      };
    };
    "data-uri-to-buffer-6.0.2" = {
      name = "data-uri-to-buffer";
      packageName = "data-uri-to-buffer";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/data-uri-to-buffer/-/data-uri-to-buffer-6.0.2.tgz";
        sha512 = "7hvf7/GW8e86rW0ptuwS3OcBGDjIi6SZva7hCyWC0yYry2cOPmLIjXAUHI6DK2HsnwJd9ifmt57i8eV2n4YNpw==";
      };
    };
    "dayjs-1.11.13" = {
      name = "dayjs";
      packageName = "dayjs";
      version = "1.11.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/dayjs/-/dayjs-1.11.13.tgz";
        sha512 = "oaMBel6gjolK862uaPQOVTA7q3TZhuSvuMQAAglQDOWYO9A91IrAOUJEyKVlqJlHE0vq5p5UXxzdPfMH/x6xNg==";
      };
    };
    "dayjs-1.8.36" = {
      name = "dayjs";
      packageName = "dayjs";
      version = "1.8.36";
      src = fetchurl {
        url = "https://registry.npmjs.org/dayjs/-/dayjs-1.8.36.tgz";
        sha512 = "3VmRXEtw7RZKAf+4Tv1Ym9AGeo8r8+CjDi26x+7SYQil1UqtqdaokhzoEJohqlzt0m5kacJSDhJQkG/LWhpRBw==";
      };
    };
    "debug-3.2.7" = {
      name = "debug";
      packageName = "debug";
      version = "3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-3.2.7.tgz";
        sha512 = "CFjzYYAi4ThfiQvizrFQevTTXHtnCqWfe7x1AhgEscTz6ZbLbfoLRLPugTQyBth6f8ZERVUSyWHFD/7Wu4t1XQ==";
      };
    };
    "debug-4.3.7" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.7.tgz";
        sha512 = "Er2nc/H7RrMXZBFCEim6TCmMk02Z8vLC2Rbi1KEBggpo0fS6l0S1nnapwmIi3yW/+GOJap1Krg4w0Hg80oCqgQ==";
      };
    };
    "debugging-stream-2.0.0" = {
      name = "debugging-stream";
      packageName = "debugging-stream";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debugging-stream/-/debugging-stream-2.0.0.tgz";
        sha512 = "xwfl6wB/3xc553uwtGnSa94jFxnGOc02C0WU2Nmzwr80gzeqn1FX4VcbvoKIhe8L/lPq4BTQttAbrTN94uN8rA==";
      };
    };
    "deffy-2.2.4" = {
      name = "deffy";
      packageName = "deffy";
      version = "2.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/deffy/-/deffy-2.2.4.tgz";
        sha512 = "pLc9lsbsWjr6RxmJ2OLyvm+9l4j1yK69h+TML/gUit/t3vTijpkNGh8LioaJYTGO7F25m6HZndADcUOo2PsiUg==";
      };
    };
    "degenerator-5.0.1" = {
      name = "degenerator";
      packageName = "degenerator";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/degenerator/-/degenerator-5.0.1.tgz";
        sha512 = "TllpMR/t0M5sqCXfj85i4XaAzxmS5tVA16dqvdkMwGmzI+dXLXnw3J+3Vdv7VKw+ThlTMboK6i9rnZ6Nntj5CQ==";
      };
    };
    "dht-rpc-6.13.0" = {
      name = "dht-rpc";
      packageName = "dht-rpc";
      version = "6.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dht-rpc/-/dht-rpc-6.13.0.tgz";
        sha512 = "5LyvidObQgya2zHkznopseVulXus7Eo4iSufCXHcXVz2RCeOUG2+AlmyU/+FFM81VewxD/m80eby4jqMdToypA==";
      };
    };
    "enquirer-2.3.6" = {
      name = "enquirer";
      packageName = "enquirer";
      version = "2.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/enquirer/-/enquirer-2.3.6.tgz";
        sha512 = "yjNnPr315/FjS4zIsUxYguYUPP2e1NK4d7E7ZOLiyYCcbFBiTMyID+2wvm2w6+pZ/odMA7cRkjhsPbltwBOrLg==";
      };
    };
    "escape-string-regexp-4.0.0" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-4.0.0.tgz";
        sha512 = "TtpcNJ3XAzx3Gq8sWRzJaVajRs0uVxA2YAkdb1jm2YkPz4G6egUFAyA3n5vtEIZefPk5Wa4UXbKuS5fKkJWdgA==";
      };
    };
    "escodegen-2.1.0" = {
      name = "escodegen";
      packageName = "escodegen";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escodegen/-/escodegen-2.1.0.tgz";
        sha512 = "2NlIDTwUWJN0mRPQOdtQBzbUHvdGY2P1VXSyU83Q3xKxM7WHX2Ql8dKq782Q9TgQUNOLEzEYu9bzLNj1q88I5w==";
      };
    };
    "esprima-4.0.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
        sha512 = "eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
      };
    };
    "estraverse-5.3.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-5.3.0.tgz";
        sha512 = "MMdARuVEQziNTeJD8DgMqmhwR11BRQ/cBP+pLtYdSTnf3MIO8fFeiINEbX36ZdNlfU/7A9f3gUw49B3oQsvwBA==";
      };
    };
    "esutils-2.0.3" = {
      name = "esutils";
      packageName = "esutils";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-2.0.3.tgz";
        sha512 = "kVscqXk4OCp68SZ0dkgEKVi6/8ij300KBWTJq32P/dYeWTSwK41WyTxalN1eRmA5Z9UU/LX9D7FWSmV9SAYx6g==";
      };
    };
    "eventemitter2-0.4.14" = {
      name = "eventemitter2";
      packageName = "eventemitter2";
      version = "0.4.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/eventemitter2/-/eventemitter2-0.4.14.tgz";
        sha512 = "K7J4xq5xAD5jHsGM5ReWXRTFa3JRGofHiMcVgQ8PRwgWxzjHpMWCIzsmyf60+mh8KLsqYPcjUMa0AC4hd6lPyQ==";
      };
    };
    "eventemitter2-5.0.1" = {
      name = "eventemitter2";
      packageName = "eventemitter2";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/eventemitter2/-/eventemitter2-5.0.1.tgz";
        sha512 = "5EM1GHXycJBS6mauYAbVKT1cVs7POKWb2NXD4Vyt8dDqeZa7LaDK1/sjtL+Zb0lzTpSNil4596Dyu97hz37QLg==";
      };
    };
    "eventemitter2-6.4.9" = {
      name = "eventemitter2";
      packageName = "eventemitter2";
      version = "6.4.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/eventemitter2/-/eventemitter2-6.4.9.tgz";
        sha512 = "JEPTiaOt9f04oa6NOkc4aH+nVp5I3wEjpHbIPqfgCdD5v5bUzy7xQqwcVO2aDQgOWhI28da57HksMrzK9HlRxg==";
      };
    };
    "extrareqp2-1.0.0" = {
      name = "extrareqp2";
      packageName = "extrareqp2";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extrareqp2/-/extrareqp2-1.0.0.tgz";
        sha512 = "Gum0g1QYb6wpPJCVypWP3bbIuaibcFiJcpuPM10YSXp/tzqi84x9PJageob+eN4xVRIOto4wjSGNLyMD54D2xA==";
      };
    };
    "fast-fifo-1.3.2" = {
      name = "fast-fifo";
      packageName = "fast-fifo";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-fifo/-/fast-fifo-1.3.2.tgz";
        sha512 = "/d9sfos4yxzpwkDkuN7k2SqFKtYNmCTzgfEpz82x34IM9/zc8KGxQoXg1liNC/izpRM/MBdt44Nmx41ZWqk+FQ==";
      };
    };
    "fast-json-patch-3.1.1" = {
      name = "fast-json-patch";
      packageName = "fast-json-patch";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-patch/-/fast-json-patch-3.1.1.tgz";
        sha512 = "vf6IHUX2SBcA+5/+4883dsIjpBTqmfBjmYiWK1savxQmFk4JfBMLa7ynTYOs1Rolp/T1betJxHiGD3g1Mn8lUQ==";
      };
    };
    "fclone-1.0.11" = {
      name = "fclone";
      packageName = "fclone";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/fclone/-/fclone-1.0.11.tgz";
        sha512 = "GDqVQezKzRABdeqflsgMr7ktzgF9CyS+p2oe0jJqUY6izSSbhPIQJDpoU4PtGcD7VPM9xh/dVrTu6z1nwgmEGw==";
      };
    };
    "fill-range-7.1.1" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-7.1.1.tgz";
        sha512 = "YsGpe3WHLK8ZYi4tWDg2Jy3ebRz2rXowDxnld4bkQB00cc/1Zw9AWnC0i9ztDJitivtQvaI9KaLyKrc+hBW0yg==";
      };
    };
    "follow-redirects-1.15.9" = {
      name = "follow-redirects";
      packageName = "follow-redirects";
      version = "1.15.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/follow-redirects/-/follow-redirects-1.15.9.tgz";
        sha512 = "gew4GsXizNgdoRyqmyfMHyAmXsZDk6mHkSxZFCzW9gwlbtOW44CDtYavM+y+72qD/Vq2l550kMF52DT8fOLJqQ==";
      };
    };
    "fs-extra-11.2.0" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "11.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-11.2.0.tgz";
        sha512 = "PmDi3uwK5nFuXh7XDTlVnS17xJS7vW36is2+w3xcv8SVxiB4NyATf4ctkVY5bkSjX0Y4nbvZCq1/EjtEyr9ktw==";
      };
    };
    "function-bind-1.1.2" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.2.tgz";
        sha512 = "7XHNxH7qX9xG5mIwxkhumTox/MIRNcOgDrxWsMt2pAr23WHp6MrRlN7FBSFpCpr+oVO0F744iUgR82nJMfG2SA==";
      };
    };
    "function.name-1.0.13" = {
      name = "function.name";
      packageName = "function.name";
      version = "1.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/function.name/-/function.name-1.0.13.tgz";
        sha512 = "mVrqdoy5npWZyoXl4DxCeuVF6delDcQjVS9aPdvLYlBxtMTZDR2B5GVEQEoM1jJyspCqg3C0v4ABkLE7tp9xFA==";
      };
    };
    "get-uri-6.0.3" = {
      name = "get-uri";
      packageName = "get-uri";
      version = "6.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-uri/-/get-uri-6.0.3.tgz";
        sha512 = "BzUrJBS9EcUb4cFol8r4W3v1cPsSyajLSthNkz5BxbpDcHN5tIrM10E2eNvfnvBn3DaT3DUgx0OpsBKkaOpanw==";
      };
    };
    "git-node-fs-1.0.0" = {
      name = "git-node-fs";
      packageName = "git-node-fs";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/git-node-fs/-/git-node-fs-1.0.0.tgz";
        sha512 = "bLQypt14llVXBg0S0u8q8HmU7g9p3ysH+NvVlae5vILuUvs759665HvmR5+wb04KjHyjFcDRxdYb4kyNnluMUQ==";
      };
    };
    "git-sha1-0.1.2" = {
      name = "git-sha1";
      packageName = "git-sha1";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/git-sha1/-/git-sha1-0.1.2.tgz";
        sha512 = "2e/nZezdVlyCopOCYHeW0onkbZg7xP1Ad6pndPy1rCygeRykefUS6r7oA5cJRGEFvseiaz5a/qUHFVX1dd6Isg==";
      };
    };
    "glob-parent-5.1.2" = {
      name = "glob-parent";
      packageName = "glob-parent";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-parent/-/glob-parent-5.1.2.tgz";
        sha512 = "AOIgSQCepiJYwP3ARnGx+5VnTu2HBYdzbGP45eLw1vr3zB3vZLeyed1sC9hnbcOc9/SrMyM5RPQrkGz4aS9Zow==";
      };
    };
    "graceful-fs-4.2.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.11.tgz";
        sha512 = "RbJ5/jmFcNNCcDV5o9eTnBLJ/HszWV0P73bc+Ff4nS/rJj+YaS6IGyiOL0VoBYX+l1Wrl3k63h/KrH+nhJ0XvQ==";
      };
    };
    "graceful-goodbye-1.3.0" = {
      name = "graceful-goodbye";
      packageName = "graceful-goodbye";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-goodbye/-/graceful-goodbye-1.3.0.tgz";
        sha512 = "hcZOs20emYlTM7MmUE0FpuZcjlk2GPsR+UYTHDeWxtGjXcbh2CawGi8vlzqsIvspqAbot7mRv3sC/uhgtKc4hQ==";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "hasown-2.0.2" = {
      name = "hasown";
      packageName = "hasown";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hasown/-/hasown-2.0.2.tgz";
        sha512 = "0hJU9SCPvmMzIBdZFqNPXWa6dqh7WdH0cII9y+CyS8rG3nL48Bclra9HmKhVVUHyPWNH5Y7xDwAB7bfgSjkUMQ==";
      };
    };
    "holesail-1.7.3" = {
      name = "holesail";
      packageName = "holesail";
      version = "1.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/holesail/-/holesail-1.7.3.tgz";
        sha512 = "NUAwMg/JEDbKH/8symfI4KCXnifzmCIybRyui21Sc9/td+DhS8XMxkZGZAQMVX8vMZ90PpEmz1ksVT5u1KQLEw==";
      };
    };
    "holesail-client-1.1.3" = {
      name = "holesail-client";
      packageName = "holesail-client";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/holesail-client/-/holesail-client-1.1.3.tgz";
        sha512 = "kssOrE4Gw+zmyLh5E0oaVpsiFB3HYMIms5m8qyisOF6kksUr1haQUpGmly+ix/alDodope9zu/sGLj18b+W/EQ==";
      };
    };
    "holesail-server-1.4.1" = {
      name = "holesail-server";
      packageName = "holesail-server";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/holesail-server/-/holesail-server-1.4.1.tgz";
        sha512 = "aukyDd6luUkhO3Jnu4ptC10Fo7x7w4EtVBoHE1YqIYRQI7g0sE//l3QPQdqVxmbx1zuxxrAwhanmljd/jM6QlQ==";
      };
    };
    "http-proxy-agent-7.0.2" = {
      name = "http-proxy-agent";
      packageName = "http-proxy-agent";
      version = "7.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-proxy-agent/-/http-proxy-agent-7.0.2.tgz";
        sha512 = "T1gkAiYYDWYx3V5Bmyu7HcfcvL7mUrTWiM6yOfa3PIphViJ/gFPbvidQ+veqSOHci/PxBcDabeUNCzpOODJZig==";
      };
    };
    "https-proxy-agent-7.0.5" = {
      name = "https-proxy-agent";
      packageName = "https-proxy-agent";
      version = "7.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/https-proxy-agent/-/https-proxy-agent-7.0.5.tgz";
        sha512 = "1e4Wqeblerz+tMKPIq2EMGiiWW1dIjZOksyHWSUm1rmuvw/how9hBHZ38lAGj5ID4Ik6EdkOw7NmWPy6LAwalw==";
      };
    };
    "hyper-cmd-lib-keys-0.0.2" = {
      name = "hyper-cmd-lib-keys";
      packageName = "hyper-cmd-lib-keys";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hyper-cmd-lib-keys/-/hyper-cmd-lib-keys-0.0.2.tgz";
        sha512 = "/KUs6yDoBzYFSlx2PnFoCDZaiNwMqc+iDsMqaXM0Wd+Ntu2nkxJxFSlxKCZUThHOmjJF3DH1SPD/5kgENpbwug==";
      };
    };
    "hyper-cmd-lib-keys-0.1.1" = {
      name = "hyper-cmd-lib-keys";
      packageName = "hyper-cmd-lib-keys";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/hyper-cmd-lib-keys/-/hyper-cmd-lib-keys-0.1.1.tgz";
        sha512 = "K1RfDEGD2WaXlSaXJTjR0dAUJ0KLts6e+IMWStkBfW7+uRjz4mCfwdgk6hysenrZerBqXlsy3ArDmnj41e0lNg==";
      };
    };
    "hypercore-crypto-3.4.2" = {
      name = "hypercore-crypto";
      packageName = "hypercore-crypto";
      version = "3.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hypercore-crypto/-/hypercore-crypto-3.4.2.tgz";
        sha512 = "16ii4M6T1dFfRa41Szv3IR0wXfImJMYJ8ysZEGwHEDH7sMeWVEBck6tg1GCNutYl39E+H7wMY2p3ndCRfj+XdQ==";
      };
    };
    "hypercore-id-encoding-1.3.0" = {
      name = "hypercore-id-encoding";
      packageName = "hypercore-id-encoding";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hypercore-id-encoding/-/hypercore-id-encoding-1.3.0.tgz";
        sha512 = "W6sHdGo5h7LXEsoWfKf/KfuROZmZRQDlGqJF2EPHW+noCK66Vvr0+zE6cL0vqQi18s0kQPeN7Sq3QyR0Ytc2VQ==";
      };
    };
    "hyperdht-6.16.5" = {
      name = "hyperdht";
      packageName = "hyperdht";
      version = "6.16.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/hyperdht/-/hyperdht-6.16.5.tgz";
        sha512 = "4X7fSGREdeBUc3u4sG7ndgjunGGAOPB9qvnlsIzoXvB+U7ZPZjSfm20RvmphR967aODEZXulctylyRevc6S0jA==";
      };
    };
    "hypertrace-1.4.2" = {
      name = "hypertrace";
      packageName = "hypertrace";
      version = "1.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hypertrace/-/hypertrace-1.4.2.tgz";
        sha512 = "sa6iq1FaJ03Db3eUl5ZodyOL3fheyrum9xzeHasXOQ/AprTT6vS1WjpbXfYkHhmzVmyn0jBW/VsCb1QaBkGyow==";
      };
    };
    "iconv-lite-0.4.24" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.24";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.24.tgz";
        sha512 = "v3MXnZAcvnywkTUEZomIActle7RXXeedOR31wwl7VlyoXO4Qi9arvSenNQWne1TcRwhCL1HwLI21bEqdpj8/rA==";
      };
    };
    "ini-1.3.8" = {
      name = "ini";
      packageName = "ini";
      version = "1.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-1.3.8.tgz";
        sha512 = "JV/yugV2uzW5iMRSiZAyDtQd+nxtUnjeLt0acNdw98kKLrvuRVyB80tsREOE7yvGVgalhZ6RNXCmEHkUKBKxew==";
      };
    };
    "ip-address-9.0.5" = {
      name = "ip-address";
      packageName = "ip-address";
      version = "9.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/ip-address/-/ip-address-9.0.5.tgz";
        sha512 = "zHtQzGojZXTwZTHQqra+ETKd4Sn3vgi7uBmlPoXVWZqYvuKmtI0l/VZTjqGmJY9x88GGOaZ9+G9ES8hC4T4X8g==";
      };
    };
    "is-binary-path-2.1.0" = {
      name = "is-binary-path";
      packageName = "is-binary-path";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-binary-path/-/is-binary-path-2.1.0.tgz";
        sha512 = "ZMERYes6pDydyuGidse7OsHxtbI7WVeUEozgR/g7rd0xUimYNlvZRE/K2MgZTjWy725IfelLeVcEM97mmtRGXw==";
      };
    };
    "is-core-module-2.15.1" = {
      name = "is-core-module";
      packageName = "is-core-module";
      version = "2.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-core-module/-/is-core-module-2.15.1.tgz";
        sha512 = "z0vtXSwucUJtANQWldhbtbt7BnL0vxiFjIdDLAatwhDYty2bad6s+rijD6Ri4YuYJubLzIJLUidCh09e1djEVQ==";
      };
    };
    "is-extglob-2.1.1" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
        sha512 = "SbKbANkN603Vi4jEZv49LeVJMn4yGwsbzZworEoyEiutsN3nJYdbO36zfhGJ6QEDpOZIFkDtnq5JRxmvl3jsoQ==";
      };
    };
    "is-glob-4.0.3" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-4.0.3.tgz";
        sha512 = "xelSayHH36ZgE7ZWhli7pW34hNbNl8Ojv5KVmkJD4hBdD3th8Tfk9vYasLM+mXWOZhFkgZfxhLSnrwRr4elSSg==";
      };
    };
    "is-number-7.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-7.0.0.tgz";
        sha512 = "41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==";
      };
    };
    "is-undefined-1.0.11" = {
      name = "is-undefined";
      packageName = "is-undefined";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-undefined/-/is-undefined-1.0.11.tgz";
        sha512 = "gRwyH8IRpV73MDlVefPllIjxBjrP9YAB0YCLtxnROhRkedTSzzBJgfxTC6HgP2/dttawQHWNZe88MvXS9Hbn/g==";
      };
    };
    "is-win-1.0.10" = {
      name = "is-win";
      packageName = "is-win";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-win/-/is-win-1.0.10.tgz";
        sha512 = "tJ9PPj5RW2RUaZ2lAIVRqQjMSynA44Ln89h+Ue+pOecoWIv6dLHvN6dtLxeCi/h5epPJPSVyuaNObLAMq62OEA==";
      };
    };
    "js-git-0.7.8" = {
      name = "js-git";
      packageName = "js-git";
      version = "0.7.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-git/-/js-git-0.7.8.tgz";
        sha512 = "+E5ZH/HeRnoc/LW0AmAyhU+mNcWBzAKE+30+IDMLSLbbK+Tdt02AdkOKq9u15rlJsDEGFqtgckc8ZM59LhhiUA==";
      };
    };
    "js-yaml-4.1.0" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-4.1.0.tgz";
        sha512 = "wpxZs9NoxZaJESJGIZTyDEaYpl0FKSA+FB9aJiyemKhMwkxQg63h4T1KJgUGHpTqPDNRcmmYLugrRjJlBtWvRA==";
      };
    };
    "jsbn-1.1.0" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-1.1.0.tgz";
        sha512 = "4bYVV3aAMtDTTu4+xsDYa6sy9GyJ69/amsu9sYF2zqjiEoZA5xJi3BrfX3uY+/IekIu7MwdObdbDWpoZdBv3/A==";
      };
    };
    "jsonfile-6.1.0" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-6.1.0.tgz";
        sha512 = "5dgndWOriYSm5cnYaJNhalLNDKOqFwyDB/rr1E9ZsGciGvKPs8R2xYGCacuf3z6K1YKDz182fd+fY3cn3pMqXQ==";
      };
    };
    "kademlia-routing-table-1.0.3" = {
      name = "kademlia-routing-table";
      packageName = "kademlia-routing-table";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/kademlia-routing-table/-/kademlia-routing-table-1.0.3.tgz";
        sha512 = "ag1nLPaCSxbLnG6zeTBoGkdm+JSUi2JHMiNynHBoRG8se2w9yfyzepF3oX1B52HOEldtbuxTde5NxbNUtnwGqA==";
      };
    };
    "lazy-1.0.11" = {
      name = "lazy";
      packageName = "lazy";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/lazy/-/lazy-1.0.11.tgz";
        sha512 = "Y+CjUfLmIpoUCCRl0ub4smrYtGGr5AOa2AKOaWelGHOGz33X/Y/KizefGqbkwfz44+cnq/+9habclf8vOmu2LA==";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "lru-cache-7.18.3" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "7.18.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-7.18.3.tgz";
        sha512 = "jumlc0BIUrS3qJGgIkWZsyfAM7NCWiBcCDhnd+3NNM5KbBmLTgHVfWBcg6W+rLUsIpzpERPsvwUP7CckAQSOoA==";
      };
    };
    "minimist-1.2.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.8.tgz";
        sha512 = "2yyAR8qBkN3YuheJanUpWC5U3bb5osDywNB8RzDVlDwDHbocAJveqqj1u8+SVD7jkWT4yvsHCpWqqWqAxb0zCA==";
      };
    };
    "mkdirp-1.0.4" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-1.0.4.tgz";
        sha512 = "vVqVZQyf3WLx2Shd0qJ9xuvqgAyKPLAiqITEtqW0oIUjzo3PePDd6fW9iFz30ef7Ysp/oiWqbhszeGWW2T6Gzw==";
      };
    };
    "module-details-from-path-1.0.3" = {
      name = "module-details-from-path";
      packageName = "module-details-from-path";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/module-details-from-path/-/module-details-from-path-1.0.3.tgz";
        sha512 = "ySViT69/76t8VhE1xXHK6Ch4NcDd26gx0MzKXLO+F7NOtnqH68d9zF94nT8ZWSxXh8ELOERsnJO/sWt1xZYw5A==";
      };
    };
    "ms-2.1.3" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.3.tgz";
        sha512 = "6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==";
      };
    };
    "mute-stream-0.0.8" = {
      name = "mute-stream";
      packageName = "mute-stream";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/mute-stream/-/mute-stream-0.0.8.tgz";
        sha512 = "nnbWWOkoWyUsTjKrhgD0dcz22mdkSnpYqbEjIm2nhwhuxlSkpywJmBo8h0ZqJdkp73mb90SssHkN4rsRaBAfAA==";
      };
    };
    "nanoassert-2.0.0" = {
      name = "nanoassert";
      packageName = "nanoassert";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoassert/-/nanoassert-2.0.0.tgz";
        sha512 = "7vO7n28+aYO4J+8w96AzhmU8G+Y/xpPDJz/se19ICsqj/momRbb9mh9ZUtkoJ5X3nTnPdhEJyc0qnM6yAsHBaA==";
      };
    };
    "napi-macros-2.2.2" = {
      name = "napi-macros";
      packageName = "napi-macros";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/napi-macros/-/napi-macros-2.2.2.tgz";
        sha512 = "hmEVtAGYzVQpCKdbQea4skABsdXW4RUh5t5mJ2zzqowJS2OyXZTU1KhDVFhx+NlWZ4ap9mqR9TcDO3LTTttd+g==";
      };
    };
    "nat-sampler-1.0.1" = {
      name = "nat-sampler";
      packageName = "nat-sampler";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/nat-sampler/-/nat-sampler-1.0.1.tgz";
        sha512 = "yQvyNN7xbqR8crTKk3U8gRgpcV1Az+vfCEijiHu9oHHsnIl8n3x+yXNHl42M6L3czGynAVoOT9TqBfS87gDdcw==";
      };
    };
    "needle-2.4.0" = {
      name = "needle";
      packageName = "needle";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/needle/-/needle-2.4.0.tgz";
        sha512 = "4Hnwzr3mi5L97hMYeNl8wRW/Onhy4nUKR/lVemJ8gJedxxUyBLm9kkrDColJvoSfwi0jCNhD+xCdOtiGDQiRZg==";
      };
    };
    "netmask-2.0.2" = {
      name = "netmask";
      packageName = "netmask";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/netmask/-/netmask-2.0.2.tgz";
        sha512 = "dBpDMdxv9Irdq66304OLfEmQ9tbNRFnFTuZiLo+bD+r332bBmMJ8GBLXklIXXgxd3+v9+KUnZaUR5PJMa75Gsg==";
      };
    };
    "node-gyp-build-4.8.2" = {
      name = "node-gyp-build";
      packageName = "node-gyp-build";
      version = "4.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-gyp-build/-/node-gyp-build-4.8.2.tgz";
        sha512 = "IRUxE4BVsHWXkV/SFOut4qTlagw2aM8T5/vnTsmrHJvVoKueJHRc/JaFND7QDDc61kLYUJ6qlZM3sqTSyx2dTw==";
      };
    };
    "noise-curve-ed-2.0.1" = {
      name = "noise-curve-ed";
      packageName = "noise-curve-ed";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/noise-curve-ed/-/noise-curve-ed-2.0.1.tgz";
        sha512 = "8HMZ40Wmarg8RQjVemLrjB49JSL6eGeOD+tlzaQW5/p+hNPfHFEMC3UZZ57zUqUprMuz6GN+gsPExpz2DWL+iA==";
      };
    };
    "noise-handshake-3.1.0" = {
      name = "noise-handshake";
      packageName = "noise-handshake";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/noise-handshake/-/noise-handshake-3.1.0.tgz";
        sha512 = "0S1qkUvMbTvZCfgr/vSkVT84YyvI4Q0OLwSc5BFxVmjaePrxAwVeXeJDY3A7N/7+qj95gZ15LaNoP9ZnBXH5Lw==";
      };
    };
    "noop6-1.0.9" = {
      name = "noop6";
      packageName = "noop6";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/noop6/-/noop6-1.0.9.tgz";
        sha512 = "DB3Hwyd89dPr5HqEPg3YHjzvwh/mCqizC1zZ8vyofqc+TQRyPDnT4wgXXbLGF4z9YAzwwTLi8pNLhGqcbSjgkA==";
      };
    };
    "normalize-path-3.0.0" = {
      name = "normalize-path";
      packageName = "normalize-path";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-path/-/normalize-path-3.0.0.tgz";
        sha512 = "6eZs5Ls3WtCisHWp9S2GUy8dqkpGi4BVSz3GaqiE6ezub0512ESztXUwUB6C6IKbQkY2Pnb/mD4WYojCRwcwLA==";
      };
    };
    "nssocket-0.6.0" = {
      name = "nssocket";
      packageName = "nssocket";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nssocket/-/nssocket-0.6.0.tgz";
        sha512 = "a9GSOIql5IqgWJR3F/JXG4KpJTA3Z53Cj0MeMvGpglytB1nxE4PdFNC0jINe27CS7cGivoynwc054EzCcT3M3w==";
      };
    };
    "pac-proxy-agent-7.0.2" = {
      name = "pac-proxy-agent";
      packageName = "pac-proxy-agent";
      version = "7.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pac-proxy-agent/-/pac-proxy-agent-7.0.2.tgz";
        sha512 = "BFi3vZnO9X5Qt6NRz7ZOaPja3ic0PhlsmCRYLOpN11+mWBCR6XJDqW5RF3j8jm4WGGQZtBA+bTfxYzeKW73eHg==";
      };
    };
    "pac-resolver-7.0.1" = {
      name = "pac-resolver";
      packageName = "pac-resolver";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pac-resolver/-/pac-resolver-7.0.1.tgz";
        sha512 = "5NPgf87AT2STgwa2ntRMr45jTKrYBGkVU36yT0ig/n/GMAa3oPqhZfIQ2kMEimReg0+t9kZViDVZ83qfVUlckg==";
      };
    };
    "pako-0.2.9" = {
      name = "pako";
      packageName = "pako";
      version = "0.2.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/pako/-/pako-0.2.9.tgz";
        sha512 = "NUcwaKxUxWrZLpDG+z/xZaCgQITkA/Dv4V/T6bw7VON6l1Xz/VnrBqrYjZQ12TamKHzITTfOEIYUj48y2KXImA==";
      };
    };
    "path-parse-1.0.7" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.7.tgz";
        sha512 = "LDJzPVEEEPR+y48z93A0Ed0yXb8pAByGWo/k5YYdYgpY2/2EsOsksJrq7lOHxryrVOn1ejG6oAp8ahvOIQD8sw==";
      };
    };
    "picomatch-2.3.1" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.1.tgz";
        sha512 = "JU3teHTNjmE2VCGFzuY8EXzCDVwEqB2a8fsIvwaStHhAWJEeVd1o1QD80CU6+ZdEXXSLbSsuLwJjkCBWqRQUVA==";
      };
    };
    "pidusage-3.0.2" = {
      name = "pidusage";
      packageName = "pidusage";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pidusage/-/pidusage-3.0.2.tgz";
        sha512 = "g0VU+y08pKw5M8EZ2rIGiEBaB8wrQMjYGFfW2QVIfyT8V+fq8YFLkvlz4bz5ljvFDJYNFCWT3PWqcRr2FKO81w==";
      };
    };
    "pm2-5.4.2" = {
      name = "pm2";
      packageName = "pm2";
      version = "5.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pm2/-/pm2-5.4.2.tgz";
        sha512 = "ynVpBwZampRH3YWLwRepZpQ7X3MvpwLIaqIdFEeBYEhaXbHmEx2KqOdxGV4T54wvKBhH3LixvU1j1bK4/sq7Tw==";
      };
    };
    "pm2-axon-4.0.1" = {
      name = "pm2-axon";
      packageName = "pm2-axon";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pm2-axon/-/pm2-axon-4.0.1.tgz";
        sha512 = "kES/PeSLS8orT8dR5jMlNl+Yu4Ty3nbvZRmaAtROuVm9nYYGiaoXqqKQqQYzWQzMYWUKHMQTvBlirjE5GIIxqg==";
      };
    };
    "pm2-axon-rpc-0.7.1" = {
      name = "pm2-axon-rpc";
      packageName = "pm2-axon-rpc";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pm2-axon-rpc/-/pm2-axon-rpc-0.7.1.tgz";
        sha512 = "FbLvW60w+vEyvMjP/xom2UPhUN/2bVpdtLfKJeYM3gwzYhoTEEChCOICfFzxkxuoEleOlnpjie+n1nue91bDQw==";
      };
    };
    "pm2-deploy-1.0.2" = {
      name = "pm2-deploy";
      packageName = "pm2-deploy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pm2-deploy/-/pm2-deploy-1.0.2.tgz";
        sha512 = "YJx6RXKrVrWaphEYf++EdOOx9EH18vM8RSZN/P1Y+NokTKqYAca/ejXwVLyiEpNju4HPZEk3Y2uZouwMqUlcgg==";
      };
    };
    "pm2-multimeter-0.1.2" = {
      name = "pm2-multimeter";
      packageName = "pm2-multimeter";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pm2-multimeter/-/pm2-multimeter-0.1.2.tgz";
        sha512 = "S+wT6XfyKfd7SJIBqRgOctGxaBzUOmVQzTAS+cg04TsEUObJVreha7lvCfX8zzGVr871XwCSnHUU7DQQ5xEsfA==";
      };
    };
    "promptly-2.2.0" = {
      name = "promptly";
      packageName = "promptly";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/promptly/-/promptly-2.2.0.tgz";
        sha512 = "aC9j+BZsRSSzEsXBNBwDnAxujdx19HycZoKgRgzWnS8eOHg1asuf9heuLprfbe739zY3IdUQx+Egv6Jn135WHA==";
      };
    };
    "protomux-3.9.2" = {
      name = "protomux";
      packageName = "protomux";
      version = "3.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/protomux/-/protomux-3.9.2.tgz";
        sha512 = "s439dAQSrCg3rohE+Vn7UJN20bBUKNu/4m/+pSNKnavo14HHPsW7BP6YtfXD63qPDRwfM8la3r4DA1EQGM8iYQ==";
      };
    };
    "proxy-agent-6.3.1" = {
      name = "proxy-agent";
      packageName = "proxy-agent";
      version = "6.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-agent/-/proxy-agent-6.3.1.tgz";
        sha512 = "Rb5RVBy1iyqOtNl15Cw/llpeLH8bsb37gM1FUfKQ+Wck6xHlbAhWGUFiTRHtkjqGTA5pSHz6+0hrPW/oECihPQ==";
      };
    };
    "proxy-from-env-1.1.0" = {
      name = "proxy-from-env";
      packageName = "proxy-from-env";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-from-env/-/proxy-from-env-1.1.0.tgz";
        sha512 = "D+zkORCbA9f1tdWRK0RaCR3GPv50cMxcrz4X8k5LTSUD1Dkw47mKJEZQNunItRTkWwgtaUSo1RVFRIG9ZXiFYg==";
      };
    };
    "qrcode-terminal-0.12.0" = {
      name = "qrcode-terminal";
      packageName = "qrcode-terminal";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/qrcode-terminal/-/qrcode-terminal-0.12.0.tgz";
        sha512 = "EXtzRZmC+YGmGlDFbXKxQiMZNwCLEO6BANKXG4iCtSIM0yqc/pappSx3RIKr4r0uh5JsBckOXeKrB3Iz7mdQpQ==";
      };
    };
    "queue-tick-1.0.1" = {
      name = "queue-tick";
      packageName = "queue-tick";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/queue-tick/-/queue-tick-1.0.1.tgz";
        sha512 = "kJt5qhMxoszgU/62PLP1CJytzd2NKetjSRnyuj31fDd3Rlcz3fzlFdFLD1SItunPwyqEOkca6GbV612BWfaBag==";
      };
    };
    "read-1.0.7" = {
      name = "read";
      packageName = "read";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/read/-/read-1.0.7.tgz";
        sha512 = "rSOKNYUmaxy0om1BNjMN4ezNT6VKK+2xF4GBhc81mkH7L60i6dp8qPYrkndNLT3QPphoII3maL9PVC9XmhHwVQ==";
      };
    };
    "readdirp-3.6.0" = {
      name = "readdirp";
      packageName = "readdirp";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readdirp/-/readdirp-3.6.0.tgz";
        sha512 = "hOS089on8RduqdbhvQ5Z37A0ESjsqz6qnRcffsMU3495FuTdqSm+7bhJ29JvIOsBDEEnan5DPu9t3To9VRlMzA==";
      };
    };
    "record-cache-1.2.0" = {
      name = "record-cache";
      packageName = "record-cache";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/record-cache/-/record-cache-1.2.0.tgz";
        sha512 = "kyy3HWCez2WrotaL3O4fTn0rsIdfRKOdQQcEJ9KpvmKmbffKVvwsloX063EgRUlpJIXHiDQFhJcTbZequ2uTZw==";
      };
    };
    "require-in-the-middle-5.2.0" = {
      name = "require-in-the-middle";
      packageName = "require-in-the-middle";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-in-the-middle/-/require-in-the-middle-5.2.0.tgz";
        sha512 = "efCx3b+0Z69/LGJmm9Yvi4cqEdxnoGnxYxGxBghkkTTFeXRtTCmmhO0AnAfHz59k957uTSuy8WaHqOs8wbYUWg==";
      };
    };
    "resolve-1.22.8" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.22.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.22.8.tgz";
        sha512 = "oKWePCxqpd6FlLvGV1VU0x7bkPmmCNolxzjMf4NczoDnQcIWrAF+cPtZn5i6n+RfD2d9i0tzpKnG6Yk168yIyw==";
      };
    };
    "run-series-1.1.9" = {
      name = "run-series";
      packageName = "run-series";
      version = "1.1.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/run-series/-/run-series-1.1.9.tgz";
        sha512 = "Arc4hUN896vjkqCYrUXquBFtRZdv1PfLbTYP71efP6butxyQ0kWpiNJyAgsxscmQg1cqvHY32/UCBzXedTpU2g==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "safety-catch-1.0.2" = {
      name = "safety-catch";
      packageName = "safety-catch";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safety-catch/-/safety-catch-1.0.2.tgz";
        sha512 = "C1UYVZ4dtbBxEtvOcpjBaaD27nP8MlvyAQEp2fOTOEe6pfUpk1cDUxij6BR1jZup6rSyUTaBBplK7LanskrULA==";
      };
    };
    "sax-1.4.1" = {
      name = "sax";
      packageName = "sax";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.4.1.tgz";
        sha512 = "+aWOz7yVScEGoKNd4PA10LZ8sk0A/z5+nXQG5giUO5rprX9jgYsTdov9qCchZiPIZezbZH+jRut8nPodFAX4Jg==";
      };
    };
    "semver-7.5.4" = {
      name = "semver";
      packageName = "semver";
      version = "7.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.5.4.tgz";
        sha512 = "1bCSESV6Pv+i21Hvpxp3Dx+pSD8lIPt8uVjRrxAUt/nbswYc+tK6Y2btiULjd4+fnq15PX+nqQDC7Oft7WkwcA==";
      };
    };
    "semver-7.6.3" = {
      name = "semver";
      packageName = "semver";
      version = "7.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.6.3.tgz";
        sha512 = "oVekP1cKtI+CTDvHWYFUcMtsK/00wmAEfyqKfNdARm8u1wNVhSgaX7A8d4UuIlUI5e84iEwOhs7ZPYRmzU9U6A==";
      };
    };
    "sha256-universal-1.2.1" = {
      name = "sha256-universal";
      packageName = "sha256-universal";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sha256-universal/-/sha256-universal-1.2.1.tgz";
        sha512 = "ghn3muhdn1ailCQqqceNxRgkOeZSVfSE13RQWEg6njB+itsFzGVSJv+O//2hvNXZuxVIRyNzrgsZ37SPDdGJJw==";
      };
    };
    "sha256-wasm-2.2.2" = {
      name = "sha256-wasm";
      packageName = "sha256-wasm";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/sha256-wasm/-/sha256-wasm-2.2.2.tgz";
        sha512 = "qKSGARvao+JQlFiA+sjJZhJ/61gmW/3aNLblB2rsgIxDlDxsJPHo8a1seXj12oKtuHVgJSJJ7QEGBUYQN741lQ==";
      };
    };
    "sha512-universal-1.2.1" = {
      name = "sha512-universal";
      packageName = "sha512-universal";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sha512-universal/-/sha512-universal-1.2.1.tgz";
        sha512 = "kehYuigMoRkIngCv7rhgruLJNNHDnitGTBdkcYbCbooL8Cidj/bS78MDxByIjcc69M915WxcQTgZetZ1JbeQTQ==";
      };
    };
    "sha512-wasm-2.3.4" = {
      name = "sha512-wasm";
      packageName = "sha512-wasm";
      version = "2.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/sha512-wasm/-/sha512-wasm-2.3.4.tgz";
        sha512 = "akWoxJPGCB3aZCrZ+fm6VIFhJ/p8idBv7AWGFng/CZIrQo51oQNsvDbTSRXWAzIiZJvpy16oIDiCCPqTe21sKg==";
      };
    };
    "shimmer-1.2.1" = {
      name = "shimmer";
      packageName = "shimmer";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/shimmer/-/shimmer-1.2.1.tgz";
        sha512 = "sQTKC1Re/rM6XyFM6fIAGHRPVGvyXfgzIDvzoq608vM+jeyVD0Tu1E6Np0Kc2zAIFWIj963V2800iF/9LPieQw==";
      };
    };
    "signal-exit-3.0.7" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.7.tgz";
        sha512 = "wnD2ZE+l+SPC/uoS0vXeE9L1+0wuaMqKlfz9AMUo38JsyLSBWSFcHR1Rri62LZc12vLr1gb3jl7iwQhgwpAbGQ==";
      };
    };
    "signal-promise-1.0.3" = {
      name = "signal-promise";
      packageName = "signal-promise";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-promise/-/signal-promise-1.0.3.tgz";
        sha512 = "WBgv0UnIq2C+Aeh0/n+IRpP6967eIx9WpynTUoiW3isPpfe1zu2LJzyfXdo9Tgef8yR/sGjcMvoUXD7EYdiz+g==";
      };
    };
    "siphash24-1.3.1" = {
      name = "siphash24";
      packageName = "siphash24";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/siphash24/-/siphash24-1.3.1.tgz";
        sha512 = "moemC3ZKiTzH29nbFo3Iw8fbemWWod4vNs/WgKbQ54oEs6mE6XVlguxvinYjB+UmaE0PThgyED9fUkWvirT8hA==";
      };
    };
    "smart-buffer-4.2.0" = {
      name = "smart-buffer";
      packageName = "smart-buffer";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/smart-buffer/-/smart-buffer-4.2.0.tgz";
        sha512 = "94hK0Hh8rPqQl2xXc3HsaBoOXKV20MToPkcXvwbISWLEs+64sBq5kFgn2kJDHb1Pry9yrP0dxrCI9RRci7RXKg==";
      };
    };
    "socks-2.8.3" = {
      name = "socks";
      packageName = "socks";
      version = "2.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/socks/-/socks-2.8.3.tgz";
        sha512 = "l5x7VUUWbjVFbafGLxPWkYsHIhEvmF85tbIeFZWc8ZPtoMyybuEhL7Jye/ooC4/d48FgOjSJXgsF/AJPYCW8Zw==";
      };
    };
    "socks-proxy-agent-8.0.4" = {
      name = "socks-proxy-agent";
      packageName = "socks-proxy-agent";
      version = "8.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/socks-proxy-agent/-/socks-proxy-agent-8.0.4.tgz";
        sha512 = "GNAq/eg8Udq2x0eNiFkr9gRg5bA7PXEWagQdeRX4cPSG+X/8V38v637gim9bjFptMk1QWsCTr0ttrJEiXbNnRw==";
      };
    };
    "sodium-javascript-0.8.0" = {
      name = "sodium-javascript";
      packageName = "sodium-javascript";
      version = "0.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sodium-javascript/-/sodium-javascript-0.8.0.tgz";
        sha512 = "rEBzR5mPxPES+UjyMDvKPIXy9ImF17KOJ32nJNi9uIquWpS/nfj+h6m05J5yLJaGXjgM72LmQoUbWZVxh/rmGg==";
      };
    };
    "sodium-native-4.2.0" = {
      name = "sodium-native";
      packageName = "sodium-native";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sodium-native/-/sodium-native-4.2.0.tgz";
        sha512 = "rdJRAf/RE/IRFUUoUsz10slNAQDTGz5ChpIeR1Ti0BtGYstl6Uok4hHALPBdnFcLml6qXJ2pDd0/De09mPa6mg==";
      };
    };
    "sodium-secretstream-1.1.0" = {
      name = "sodium-secretstream";
      packageName = "sodium-secretstream";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sodium-secretstream/-/sodium-secretstream-1.1.0.tgz";
        sha512 = "Qg7D2xomELDjDCWAmE4izk1aecG/il8pQIGmSWFaKgah/V58BVWG/PuSZF6vseTpcqnetIFGaOWzmPNzyTD50A==";
      };
    };
    "sodium-universal-4.0.1" = {
      name = "sodium-universal";
      packageName = "sodium-universal";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sodium-universal/-/sodium-universal-4.0.1.tgz";
        sha512 = "sNp13PrxYLaUFHTGoDKkSDFvoEu51bfzE12RwGlqU1fcrkpAOK0NvizaJzOWV0Omtk9me2+Pnbjcf/l0efxuGQ==";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "source-map-support-0.5.21" = {
      name = "source-map-support";
      packageName = "source-map-support";
      version = "0.5.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-support/-/source-map-support-0.5.21.tgz";
        sha512 = "uBHU3L3czsIyYXKX88fdrGovxdSCoTGDRZ6SYXtSRxLZUzHg5P/66Ht6uoUlHu9EZod+inXhKo3qQgwXUT/y1w==";
      };
    };
    "sprintf-js-1.1.2" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.1.2.tgz";
        sha512 = "VE0SOVEHCk7Qc8ulkWw3ntAzXuqf7S2lvwQaDLRnUeIEaKNQJzV6BwmLKhOqT61aGhfUMrXeaBk+oDGCzvhcug==";
      };
    };
    "sprintf-js-1.1.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.1.3.tgz";
        sha512 = "Oo+0REFV59/rz3gfJNKQiBlwfHaSESl1pcGyABQsnnIfWOFt6JNj5gCog2U6MLZ//IGYD+nA8nI+mTShREReaA==";
      };
    };
    "streamx-2.20.1" = {
      name = "streamx";
      packageName = "streamx";
      version = "2.20.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/streamx/-/streamx-2.20.1.tgz";
        sha512 = "uTa0mU6WUC65iUvzKH4X9hEdvSW7rbPxPtwfWiLMSj3qTdQbAiUboZTxauKfpFuGIGa1C2BYijZ7wgdUXICJhA==";
      };
    };
    "supports-color-7.2.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz";
        sha512 = "qpCAvRl9stuOHveKsn7HncJRvv501qIacKzQlO/+Lwxc9+0q2wLyv4Dfvt80/DPn2pqOBsJdDiogXGR9+OvwRw==";
      };
    };
    "supports-preserve-symlinks-flag-1.0.0" = {
      name = "supports-preserve-symlinks-flag";
      packageName = "supports-preserve-symlinks-flag";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-preserve-symlinks-flag/-/supports-preserve-symlinks-flag-1.0.0.tgz";
        sha512 = "ot0WnXS9fgdkgIcePe6RHNk1WA8+muPa6cSjeR3V8K27q9BB1rTE3R1p7Hv0z1ZyAc8s6Vvv8DIyWf681MAt0w==";
      };
    };
    "text-decoder-1.2.0" = {
      name = "text-decoder";
      packageName = "text-decoder";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/text-decoder/-/text-decoder-1.2.0.tgz";
        sha512 = "n1yg1mOj9DNpk3NeZOx7T6jchTbyJS3i3cucbNN6FcdPriMZx7NsgrGpWWdWZZGxD7ES1XB+3uoqHMgOKaN+fg==";
      };
    };
    "time-ordered-set-1.0.2" = {
      name = "time-ordered-set";
      packageName = "time-ordered-set";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/time-ordered-set/-/time-ordered-set-1.0.2.tgz";
        sha512 = "vGO99JkxvgX+u+LtOKQEpYf31Kj3i/GNwVstfnh4dyINakMgeZCpew1e3Aj+06hEslhtHEd52g7m5IV+o1K8Mw==";
      };
    };
    "timeout-refresh-2.0.1" = {
      name = "timeout-refresh";
      packageName = "timeout-refresh";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/timeout-refresh/-/timeout-refresh-2.0.1.tgz";
        sha512 = "SVqEcMZBsZF9mA78rjzCrYrUs37LMJk3ShZ851ygZYW1cMeIjs9mL57KO6Iv5mmjSQnOe/29/VAfGXo+oRCiVw==";
      };
    };
    "to-regex-range-5.0.1" = {
      name = "to-regex-range";
      packageName = "to-regex-range";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-regex-range/-/to-regex-range-5.0.1.tgz";
        sha512 = "65P7iz6X5yEr1cwcgvQxbbIw7Uk3gOy5dIdtZ4rDveLqhrdJP+Li/Hx6tyK0NEb+2GCyneCMJiGqrADCSNk8sQ==";
      };
    };
    "tslib-1.9.3" = {
      name = "tslib";
      packageName = "tslib";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-1.9.3.tgz";
        sha512 = "4krF8scpejhaOgqzBEcGM7yDIEfi0/8+8zDRZhNZZ2kjmHJ4hv3zCbQWxoJGz1iw5U0Jl0nma13xzHXcncMavQ==";
      };
    };
    "tslib-2.7.0" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.7.0.tgz";
        sha512 = "gLXCKdN1/j47AiHiOkJN69hJmcbGTHI0ImLmbYLHykhgeN0jVGola9yVjFgzCUklsZQMW55o+dW7IXv3RCXDzA==";
      };
    };
    "tv4-1.3.0" = {
      name = "tv4";
      packageName = "tv4";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tv4/-/tv4-1.3.0.tgz";
        sha512 = "afizzfpJgvPr+eDkREK4MxJ/+r8nEEHcmitwgnPUqpaP+FpwQyadnxNoSACbgc/b1LsZYtODGoPiFxQrgJgjvw==";
      };
    };
    "typpy-2.3.13" = {
      name = "typpy";
      packageName = "typpy";
      version = "2.3.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/typpy/-/typpy-2.3.13.tgz";
        sha512 = "vOxIcQz9sxHi+rT09SJ5aDgVgrPppQjwnnayTrMye1ODaU8gIZTDM19t9TxmEElbMihx2Nq/0/b/MtyKfayRqA==";
      };
    };
    "udx-native-1.12.1" = {
      name = "udx-native";
      packageName = "udx-native";
      version = "1.12.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/udx-native/-/udx-native-1.12.1.tgz";
        sha512 = "E/2gwAxRTYA+TtU/z8dyognBMjEDVKB8dwWJQeVouHq6nGo3n2aiSxxxku+CSoJjnNUM60vw9b/qZvu+DHkA8g==";
      };
    };
    "ul-5.2.15" = {
      name = "ul";
      packageName = "ul";
      version = "5.2.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/ul/-/ul-5.2.15.tgz";
        sha512 = "svLEUy8xSCip5IWnsRa0UOg+2zP0Wsj4qlbjTmX6GJSmvKMHADBuHOm1dpNkWqWPIGuVSqzUkV3Cris5JrlTRQ==";
      };
    };
    "universalify-2.0.1" = {
      name = "universalify";
      packageName = "universalify";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/universalify/-/universalify-2.0.1.tgz";
        sha512 = "gptHNQghINnc/vTGIk0SOFGFNXw7JVrlRUtConJRlvaw6DuX0wO5Jeko9sWrMBhh+PsYAZ7oXAiOnf/UKogyiw==";
      };
    };
    "unslab-1.3.0" = {
      name = "unslab";
      packageName = "unslab";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unslab/-/unslab-1.3.0.tgz";
        sha512 = "YATkfKAFj47kTzmiQrWXMyRvaVrHsW6MEALa4bm+FhiA2YG4oira+Z3DXN6LrYOYn2Y8eO94Lwl9DOHjs1FpoQ==";
      };
    };
    "utf-8-validate-5.0.10" = {
      name = "utf-8-validate";
      packageName = "utf-8-validate";
      version = "5.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/utf-8-validate/-/utf-8-validate-5.0.10.tgz";
        sha512 = "Z6czzLq4u8fPOyx7TU6X3dvUZVvoJmxSQ+IcrlmagKhilxlhZgxPK6C5Jqbkw1IDUmFTM+cz9QDnnLTwDz/2gQ==";
      };
    };
    "vizion-2.2.1" = {
      name = "vizion";
      packageName = "vizion";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vizion/-/vizion-2.2.1.tgz";
        sha512 = "sfAcO2yeSU0CSPFI/DmZp3FsFE9T+8913nv1xWBOyzODv13fwkn6Vl7HqxGpkr9F608M+8SuFId3s+BlZqfXww==";
      };
    };
    "ws-7.5.10" = {
      name = "ws";
      packageName = "ws";
      version = "7.5.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-7.5.10.tgz";
        sha512 = "+dbF1tHwZpXcbOJdVOkzLDxZP1ailvSxM6ZweXTegylPny803bFhA+vqBYw4s31NSAk4S2Qz+AKXK9a4wkdjcQ==";
      };
    };
    "xache-1.2.1" = {
      name = "xache";
      packageName = "xache";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xache/-/xache-1.2.1.tgz";
        sha512 = "igRS6jPreJ54ABdzhh4mCDXcz+XMaWO2q1ABRV2yWYuk29jlp8VT7UBdCqNkX7rpYBbXsebVVKkwIuYZjyZNqA==";
      };
    };
    "xsalsa20-1.2.0" = {
      name = "xsalsa20";
      packageName = "xsalsa20";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xsalsa20/-/xsalsa20-1.2.0.tgz";
        sha512 = "FIr/DEeoHfj7ftfylnoFt3rAIRoWXpx2AoDfrT2qD2wtp7Dp+COajvs/Icb7uHqRW9m60f5iXZwdsJJO3kvb7w==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
    "z32-1.1.0" = {
      name = "z32";
      packageName = "z32";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/z32/-/z32-1.1.0.tgz";
        sha512 = "1WUHy+VS6d0HPNspDxvLssBbeQjXMjSnpv0vH82vRAUfg847NmX3OXozp/hRP5jPhxBbrVzrgvAt+UsGNzRFQQ==";
      };
    };
  };
  args = {
    name = "node2nix";
    packageName = "node2nix";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."@holesail/hyper-cmd-lib-net-0.1.0"
      sources."@hyperswarm/secret-stream-6.6.3"
      (sources."@pm2/agent-2.0.4" // {
        dependencies = [
          sources."dayjs-1.8.36"
          sources."semver-7.5.4"
        ];
      })
      (sources."@pm2/io-6.0.1" // {
        dependencies = [
          sources."async-2.6.4"
          sources."eventemitter2-6.4.9"
          sources."semver-7.5.4"
        ];
      })
      (sources."@pm2/js-api-0.8.0" // {
        dependencies = [
          sources."async-2.6.4"
          sources."eventemitter2-6.4.9"
        ];
      })
      sources."@pm2/pm2-version-check-1.0.4"
      sources."@tootallnate/quickjs-emscripten-0.23.0"
      sources."agent-base-7.1.1"
      sources."amp-0.3.1"
      sources."amp-message-0.1.2"
      sources."ansi-colors-4.1.3"
      sources."ansi-parser-3.2.10"
      sources."ansi-styles-4.3.0"
      sources."anymatch-3.1.3"
      sources."argparse-2.0.1"
      (sources."ast-types-0.13.4" // {
        dependencies = [
          sources."tslib-2.7.0"
        ];
      })
      sources."async-3.2.6"
      sources."b4a-1.6.6"
      sources."bare-dns-1.0.4"
      sources."bare-events-2.4.2"
      sources."bare-net-1.0.1"
      sources."bare-pipe-3.3.6"
      sources."bare-stream-2.3.0"
      sources."bare-tcp-1.9.0"
      sources."basic-ftp-5.0.5"
      sources."binary-extensions-2.3.0"
      sources."bits-to-bytes-1.3.0"
      sources."blake2b-2.1.4"
      sources."blake2b-wasm-2.4.0"
      sources."blessed-0.1.81"
      sources."blind-relay-1.3.3"
      sources."bodec-0.1.0"
      sources."bogon-1.1.0"
      sources."braces-3.0.3"
      sources."buffer-from-1.1.2"
      sources."bufferutil-4.0.8"
      sources."chacha20-universal-1.0.4"
      sources."chalk-3.0.0"
      sources."charm-0.1.2"
      sources."chokidar-3.6.0"
      sources."cli-box-6.0.10"
      sources."cli-tableau-2.0.1"
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."colors-1.4.0"
      sources."commander-2.15.1"
      sources."compact-encoding-2.15.0"
      sources."compact-encoding-bitfield-1.0.0"
      sources."compact-encoding-net-1.2.0"
      sources."croner-4.1.97"
      sources."culvert-0.1.2"
      sources."data-uri-to-buffer-6.0.2"
      sources."dayjs-1.11.13"
      sources."debug-4.3.7"
      sources."debugging-stream-2.0.0"
      sources."deffy-2.2.4"
      sources."degenerator-5.0.1"
      sources."dht-rpc-6.13.0"
      sources."enquirer-2.3.6"
      sources."escape-string-regexp-4.0.0"
      sources."escodegen-2.1.0"
      sources."esprima-4.0.1"
      sources."estraverse-5.3.0"
      sources."esutils-2.0.3"
      sources."eventemitter2-5.0.1"
      sources."extrareqp2-1.0.0"
      sources."fast-fifo-1.3.2"
      sources."fast-json-patch-3.1.1"
      sources."fclone-1.0.11"
      sources."fill-range-7.1.1"
      sources."follow-redirects-1.15.9"
      sources."fs-extra-11.2.0"
      sources."function-bind-1.1.2"
      sources."function.name-1.0.13"
      sources."get-uri-6.0.3"
      sources."git-node-fs-1.0.0"
      sources."git-sha1-0.1.2"
      sources."glob-parent-5.1.2"
      sources."graceful-fs-4.2.11"
      sources."graceful-goodbye-1.3.0"
      sources."has-flag-4.0.0"
      sources."hasown-2.0.2"
      sources."holesail-1.7.3"
      (sources."holesail-client-1.1.3" // {
        dependencies = [
          sources."hyper-cmd-lib-keys-0.0.2"
        ];
      })
      (sources."holesail-server-1.4.1" // {
        dependencies = [
          sources."hyper-cmd-lib-keys-0.0.2"
        ];
      })
      sources."http-proxy-agent-7.0.2"
      sources."https-proxy-agent-7.0.5"
      sources."hyper-cmd-lib-keys-0.1.1"
      sources."hypercore-crypto-3.4.2"
      sources."hypercore-id-encoding-1.3.0"
      sources."hyperdht-6.16.5"
      sources."hypertrace-1.4.2"
      sources."iconv-lite-0.4.24"
      sources."ini-1.3.8"
      (sources."ip-address-9.0.5" // {
        dependencies = [
          sources."sprintf-js-1.1.3"
        ];
      })
      sources."is-binary-path-2.1.0"
      sources."is-core-module-2.15.1"
      sources."is-extglob-2.1.1"
      sources."is-glob-4.0.3"
      sources."is-number-7.0.0"
      sources."is-undefined-1.0.11"
      sources."is-win-1.0.10"
      sources."js-git-0.7.8"
      sources."js-yaml-4.1.0"
      sources."jsbn-1.1.0"
      sources."jsonfile-6.1.0"
      sources."kademlia-routing-table-1.0.3"
      sources."lazy-1.0.11"
      sources."lodash-4.17.21"
      sources."lru-cache-6.0.0"
      sources."minimist-1.2.8"
      sources."mkdirp-1.0.4"
      sources."module-details-from-path-1.0.3"
      sources."ms-2.1.3"
      sources."mute-stream-0.0.8"
      sources."nanoassert-2.0.0"
      sources."napi-macros-2.2.2"
      sources."nat-sampler-1.0.1"
      (sources."needle-2.4.0" // {
        dependencies = [
          sources."debug-3.2.7"
        ];
      })
      sources."netmask-2.0.2"
      sources."node-gyp-build-4.8.2"
      sources."noise-curve-ed-2.0.1"
      sources."noise-handshake-3.1.0"
      sources."noop6-1.0.9"
      sources."normalize-path-3.0.0"
      (sources."nssocket-0.6.0" // {
        dependencies = [
          sources."eventemitter2-0.4.14"
        ];
      })
      sources."pac-proxy-agent-7.0.2"
      sources."pac-resolver-7.0.1"
      sources."pako-0.2.9"
      sources."path-parse-1.0.7"
      sources."picomatch-2.3.1"
      sources."pidusage-3.0.2"
      sources."pm2-5.4.2"
      sources."pm2-axon-4.0.1"
      sources."pm2-axon-rpc-0.7.1"
      sources."pm2-deploy-1.0.2"
      sources."pm2-multimeter-0.1.2"
      sources."promptly-2.2.0"
      sources."protomux-3.9.2"
      (sources."proxy-agent-6.3.1" // {
        dependencies = [
          sources."lru-cache-7.18.3"
        ];
      })
      sources."proxy-from-env-1.1.0"
      sources."qrcode-terminal-0.12.0"
      sources."queue-tick-1.0.1"
      sources."read-1.0.7"
      sources."readdirp-3.6.0"
      sources."record-cache-1.2.0"
      sources."require-in-the-middle-5.2.0"
      sources."resolve-1.22.8"
      sources."run-series-1.1.9"
      sources."safe-buffer-5.2.1"
      sources."safer-buffer-2.1.2"
      sources."safety-catch-1.0.2"
      sources."sax-1.4.1"
      sources."semver-7.6.3"
      sources."sha256-universal-1.2.1"
      sources."sha256-wasm-2.2.2"
      sources."sha512-universal-1.2.1"
      sources."sha512-wasm-2.3.4"
      sources."shimmer-1.2.1"
      sources."signal-exit-3.0.7"
      sources."signal-promise-1.0.3"
      sources."siphash24-1.3.1"
      sources."smart-buffer-4.2.0"
      sources."socks-2.8.3"
      sources."socks-proxy-agent-8.0.4"
      sources."sodium-javascript-0.8.0"
      sources."sodium-native-4.2.0"
      sources."sodium-secretstream-1.1.0"
      sources."sodium-universal-4.0.1"
      sources."source-map-0.6.1"
      sources."source-map-support-0.5.21"
      sources."sprintf-js-1.1.2"
      sources."streamx-2.20.1"
      sources."supports-color-7.2.0"
      sources."supports-preserve-symlinks-flag-1.0.0"
      sources."text-decoder-1.2.0"
      sources."time-ordered-set-1.0.2"
      sources."timeout-refresh-2.0.1"
      sources."to-regex-range-5.0.1"
      sources."tslib-1.9.3"
      sources."tv4-1.3.0"
      sources."typpy-2.3.13"
      sources."udx-native-1.12.1"
      sources."ul-5.2.15"
      sources."universalify-2.0.1"
      sources."unslab-1.3.0"
      sources."utf-8-validate-5.0.10"
      (sources."vizion-2.2.1" // {
        dependencies = [
          sources."async-2.6.4"
        ];
      })
      sources."ws-7.5.10"
      sources."xache-1.2.1"
      sources."xsalsa20-1.2.0"
      sources."yallist-4.0.0"
      sources."z32-1.1.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "";
      license = "ISC";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
